In [4]:
#!/usr/bin/env python

# make sure to install these packages before running:
%pip install pandas
%pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("www.dallasopendata.com", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(www.dallasopendata.com,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("d7e7-envw", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

Requirement already satisfied: pandas in c:\users\saraz\downloads\desktop\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saraz\downloads\desktop\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\saraz\downloads\desktop\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

Collecting sodapy
  Downloading sodapy-2.2.0-py2.py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests>=2.28.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from sodapy) (2.32.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saraz\downloads\desktop\lib\site-packages (from requests>=2.28.1->sodapy) (2024.6.2)
Downloading sodapy-2.2.0-py2.py3-none-any.whl (15 kB)
Installing collected packages: sodapy
Successfully installed sodapy-2.2.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
results_df

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
0,22-00546350,"2523 DUNLOE DR, DALLAS, TX, 75228",9,Sanitation Services,Dead Animal Pick Up - DAS,1 Business Days,2022-12-20T00:59:00.000,Closed,2022-12-17T12:05:32.000,2025-09-30T23:10:14.000,2022-12-17T13:34:49.000,Final Results,Dispatch,Phone,5008z000004UXpbAAG,"(32.83885747145123000,-96.67070397400998000)"
1,26-00156034,"1523 E ELMORE AVE, DALLAS, TX, 75216",4,311 Customer Service Center,Water/Wastewater Line Locate - 311,1 Business Days,2026-04-16T23:59:00.000,Closed,2026-04-14T16:15:29.000,2026-04-15T11:50:21.000,2026-04-15T11:50:02.000,Information Provided,Standard,API,500cs00001i20F3AAI,"(32.71714568318380000,-96.80243314806862000)"
2,25-00036138,"732 E JEFFERSON BLVD, DALLAS, TX, 75203",1,Sanitation Services,Dead Animal Pick Up - DAS,1 Business Days,2025-01-28T18:59:00.000,Closed,2025-01-27T17:53:36.000,2025-09-30T23:10:14.000,2025-01-27T19:20:10.000,Final Results,Dispatch,API,500cs00000S3baqAAB,"(32.74842699908927000,-96.81330980501578000)"
3,22-00316016,"1703 MCBROOM ST, DALLAS, TX, 75212",6,Sanitation Services,Dead Animal Pick Up - DAS,1 Business Days,2022-07-27T23:59:00.000,Closed,2022-07-26T08:09:56.000,2025-09-30T23:10:14.000,2022-07-26T14:13:28.000,Work Completed,Dispatch,Phone,5008z0000030bmAAAQ,"(32.78273384242462600,-96.84644888677680000)"
4,25-00084964,"10562 DAWN DR, DALLAS, TX, 75228",9,Code Compliance,Code Concern - CCS,4 Business Days,NaN,Closed,2025-02-27T09:09:50.000,2025-02-27T17:09:14.000,2025-02-27T16:23:25.000,NaN,Standard,API,500cs00000WN7BHAA1,"(32.84047793150072000,-96.68103518403810000)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,26-00090921,"3815 VANCOUVER CIR, DALLAS, TX, 75229",13,Sanitation,Sanitation Roll Cart Maintenance/Delivery - SAN,3 Business Days,2026-03-13T23:59:00.000,Closed,2026-03-06T12:37:01.000,2026-03-09T16:41:29.000,2026-03-09T16:41:11.000,Service Complete,Standard,API,500cs00001aAPHgAAO,"(32.89666175283165000,-96.85133786513003000)"
1996,21-00883700,"PARKDALE DR & WILKES AVE, DALLAS, TX, 75227",5,Transportation,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2021-10-14T23:59:00.000,Closed,2021-09-29T09:49:13.000,2023-06-09T00:07:01.000,2021-10-07T09:42:56.000,Work Completed,Standard,Phone,500t000000rkuUOAAY,"(32.77107375073889000,-96.70336149535800000)"
1997,23-00341479,"7822 JACOBIE BLVD, DALLAS, TX, 75217",5,Sanitation,Sanitation Roll Cart Maintenance/Delivery - SAN,3 Business Days,2023-08-01T23:59:00.000,Closed,2023-07-25T13:12:38.000,2023-07-27T12:35:53.000,2023-07-27T12:35:52.000,Service Complete,Standard,Phone,5008z000005zBy8AAE,"(32.72358878106974000,-96.68796155508822000)"
1998,24-00060938,"3503 ALASKA AVE, DALLAS, TX, 75216",4,Dallas Animal Services,Animal Loose - DAS,1 Calendar Days,2024-02-11T00:59:00.000,Closed,2024-02-07T19:26:37.000,2024-02-08T00:30:27.000,2024-02-08T00:30:27.000,Final Results,Dispatch,Phone,5008z000007DgDVAA0,"(32.70173611790379000,-96.81610707564903000)"
1999,26-00207824,"3710 N HAMPTON RD, DALLAS, TX, 75212",6,Code Compliance,Code Concern - CCS,4 Business Days,NaN,In Progress,2026-05-14T16:03:32.000,2026-05-15T16:27:53.000,NaN,NaN,Standard,Proactive,500cs00001p3R5qAAE,"(32.78731608397680500,-96.85625692799036000)"

In [6]:
results_df["Traffic Sign - Maintenance (Other) - TRN	"]

KeyError: 'Traffic Sign - Maintenance (Other) - TRN\t'

In [7]:
traffic_signs = results_df[
    results_df["service_request_type"] == "Traffic Sign - Maintenance (Other) - TRN"
]

traffic_signs.head()

,service_request_number,address,city_council_district,department,service_request_type,ert_estimated_response_time,overall_service_request_due_date,status,created_date,update_date,closed_date,outcome,priority,method_received_description,unique_key,lat_location
61,22-00275358,"THURSTON DR & EMPIRE CENTRAL, DALLAS, TX, 75235",2,Transportation,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2022-07-14T23:59:00.000,Closed,2022-06-29T15:32:32.000,2023-06-08T23:24:45.000,2022-06-30T06:57:11.000,No Action Required,Standard,API,5008z000002jpAqAAI,"(32.83146180859601000,-96.84835919148941000)"
155,22-00275278,"GILFORD ST & DENTON DR, DALLAS, TX, 75235",2,Transportation and Public Works Department,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2022-07-14T23:59:00.000,Closed,2022-06-29T15:11:54.000,2023-06-08T23:24:45.000,2022-07-06T12:40:58.000,Work Completed,Standard,API,5008z000002jnuiAAA,"(32.83865980353513000,-96.85339158627497000)"
222,21-00442771,"1200 URBAN LOFTS DR, DALLAS, TX, 75215",2,Transportation and Public Works Department,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2021-06-01T23:59:00.000,Closed,2021-05-17T14:46:12.000,2023-06-09T00:56:45.000,2021-05-20T10:50:19.000,Work Completed,Standard,API,500t000000mA6A9AAK,"(32.76814763577979000,-96.79188042510144000)"
310,22-00238481,"FAWN VALLEY DR & FAWN RIDGE DR, DALLAS, TX, 75224",4,Transportation,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2022-06-22T23:59:00.000,Closed,2022-06-07T15:28:43.000,2023-06-08T23:17:04.000,2022-06-09T14:05:14.000,Work Completed,Standard,Proactive,5008z000002OXFPAA4,"(32.70083385838205000,-96.83452703741956000)"
386,21-00442971,"3415 CEDAR SPRINGS RD, DALLAS, TX, 75219",14,Transportation,Traffic Sign - Maintenance (Other) - TRN,3 Business Days,2021-06-01T23:59:00.000,Closed,2021-05-17T15:09:37.000,2023-06-09T00:56:47.000,2021-05-20T12:51:34.000,Work Completed,Standard,API,500t000000mA7ECAA0,"(32.80596190934913600,-96.80502526744736000)"

In [8]:
 results_df["service_request_type"].unique()

array(['Dead Animal Pick Up - DAS', 'Water/Wastewater Line Locate - 311',
       'Code Concern - CCS', 'Barricades - Pickup/Reset/Replace - TPW',
       'Extra Police Patrol - DPD', 'Parking - Report a Violation - TPW',
       'Sanitation Roll Cart Maintenance/Delivery - SAN',
       'Building Permits Violation - DEV',
       'Street Repair - Routine - TPW', 'Traffic Signal - Flashing - TRN',
       'Narcotics/Vice Complaint - DPD', 'Street Repair - Routine - PBW',
       'Complaint/Compliment - 311',
       'Scooter/Bike Shared Dockless Vehicle - TPW',
       'Utility Cut/Routine - TPW', 'Animal Bite - DAS',
       'Alley Repair - Routine - TPW',
       'Parking - Report a Violation - TRN',
       'Lid Cover Broken - Routine - TPW',
       'Traffic Signal - Knockdown - TRN', 'Traffic Sign - New - TRN',
       'Traffic Signal - Bulb Out/NonConflict Hd Trn VO - TPW',
       'Inlet/Storm Drain Cleaning - DWU', 'Shopping Carts - PBW',
       'Sanitation Missed Recycle - SAN', 'Utility Cut/Routine - PBW',
       'Sanitation Missed Brush/Bulk - SAN',
       'Restaurant/Food Complaint - CCS',
       'Traffic Sign - Maintenance (Other) - TRN',
       'Homeless Encampment - OHS', 'Shopping Cart Routine Pickup - PBW',
       'Wheel Chair Ramp/Curb Cuts - PBW',
       'Sanitation District Billing Dispute - SAN',
       'Homeless Encampment - EMCR',
       'Single Family Rental Needs Registration - CCS',
       'Traffic - Speed Control - TRN',
       'Traffic Markings - Maintenance - TRN',
       'Traffic Signal -\xa0Visibility Obstruction\xa0- TRN',
       'Street Lighting - Maintenance- TPW',
       'Sanitation Missed Garbage - SAN',
       'Traffic Signal - Other Dispatch - TRN',
       'Alley/Sidewalk/Street Repair - Hazardous - TPW',
       'Pot Hole - Routine - TPW', 'Traffic Signal - Flashing - TPW',
       'Animal Confined - DAS', 'Pot Hole - Routine - PBW',
       'Traffic Signal - Knockdown - TPW',
       'Water/Sanitary Sewer Construction Project - DWU',
       'Animal Aggressive Behavior - DAS',
       'Chronic Noise Complaint - DPD',
       'Animal Community Cat Program - DAS',
       'Traffic Violations (Chronic) - DPD', 'Animal Loose - DAS',
       'Snow/Ice Sanding - Hazardous - PBW', 'Traffic Sign - New - TPW',
       'Traffic Signal - School Flasher Maintenance - TRN',
       'Animal Nuisance - DAS', 'Shopping Cart Routine Pickup - TPW',
       'Traffic Sign - Knockdown - TRN',
       'Construction Site Complaint - PDD',
       'Consumer Protection Complaint - CCS',
       'Street Spillage/Debris in Right of Way - Hazardous - PBW',
       'Median/Right of Way Maintenance - PBW',
       'Animal Owner Surrender - DAS', 'Clean Sweep Litter Removal - TPW',
       'Flooding - Emergency - PBW',
       'Sanitation Annual 20 Cubic Yard Exemption - SAN',
       'Traffic Signal - Bulb Out/NonConflict Hd Trn VO - TRN',
       'Tree Down/Low Limbs - PBW', 'Traffic - Construction Signs - TPW',
       'Animal Lack of Care - DAS', 'Pot Hole - Hazardous - TPW',
       'Alley/Sidewalk/Street Repair - Hazardous - PBW',
       'Sidewalk Replacement Program - PBW',
       'Traffic Signal - Other Dispatch - TPW',
       'Traffic Markings - Maintenance - TPW',
       'Mobile Food Complaint - CCS',
       'Street Lighting- New/Relocation - TPW', 'Shopping Carts - TPW',
       'Utility Complaint/Information - BMS',
       'New Street/Sidewalk/Alley - PBW',
       'Sidewalk Replacement Program - TPW',
       'Traffic - Speed Control - TPW',
       'Lid Cover Broken/Missing - Hazardous - PBW',
       'Library Concerns - LIB', 'Dead Animal Pick Up - SAN',
       'Graffiti Traffic Signal - TRN',
       'Inlet/Storm Drain Stopped Up - Hazardous - DWU',
       'Utility Cut/Hazardous - PBW', 'Railroad Crossing Repair - TPW',
       'Traffic Signal - All Out - TRN', 'Traffic Signal - Timing - TPW',
       'Street Lighting - Maintenance- TRN',
       'Median/Right of Way Maintenance - TPW',
       'Sanitation Commercial Services - SAN',
       'Sanitation Same Day Missed Collection - SAN',
       'Alley Repair - Routine - PBW', 'Traffic Signal - All Out - TPW',
       'Street/Road/Driveway Blockage - TPW',
       'Park Maintenance/Misc - PKR', 'Storm Sewer Line Locate - DWU',
       'Criminal Activities - DPD', 'Tree Down/Low Limbs - TPW',
       'Construction Right of Way/Status - PBW',
       'Pot Hole - Hazardous - PBW', 'Yard Waste - OEQS',
       'Traffic Signal - Head Turn (Conflicting) - TRN',
       'Traffic Signal - Head Turn (Conflicting) - TPW',
       '24 Hour Parking Violation - DPD',
       'Traffic Sign - Maintenance (Other) - TPW',
       'Street/Road Blockage - TPW', 'Smoke Detector Request - DFR',
       'New Street/Sidewalk/Alley - TPW', 'Animal Wildlife - DAS',
       'Visibility Obstruction - Hazardous - TPW',
       'Illegal Dumping Urgent - OEQS',
       'Miscellaneous Service Request - 311', 'Panhandling - DPD',
       'Emergency Regulations Violation - CCS', 'Water Questions - 311',
       'Boarding Home Complaint - CCS', 'Traffic Signal - New - TPW',
       'Construction Right of Way/Status - TPW',
       'Traffic Sign - Knockdown - TPW',
       'Construction Site Complaint - DEV',
       'Visibility Obstruction - TPW', 'Traffic Signal - Stuck - TRN',
       'Sewer Problems - DWU', 'Sanitation Cost-Plus - SAN',
       'Street Lighting- New/Relocation - TRN',
       'Lid Cover Broken/Missing - Hazardous - TPW',
       'Paving Street Resurface Program - TPW',
       'Lid Cover Broken - Routine - PBW',
       'Street Spillage/Debris in Right of Way - Hazardous - TPW',
       'Paving Street Resurface Program - PBW',
       'Traffic Markings - New - TRN', 'Water Main Leak/Break - DWU',
       'Traffic Signal - Stuck - TPW',
       'Sanitation Commercial Roll Cart Services - SAN',
       'Homeless Encampment - ECR',
       'ICR Consumer Protection Complaint - CCS',
       'Objects Dropped in Inlet - Hazardous - TPW',
       'Graffiti Traffic Signal - TPW',
       'Historic District Violation - PDD',
       'Drainage Ditch Cleaning/Repairs - TPW',
       'Graffiti City Streets & Bridges - PBW',
       'Building Permits Violation - SDC',
       'Building Permits Violation - PDD',
       'Storm Drainage/Flooding Complaint - DWU',
       'Sanitation Property Damage - SAN',
       'Handicap Parking Violation - DPD', 'Traffic Signal - New - TRN',
       'Utility Complaint/Information - OBS', 'Animal Loose Cat - DAS',
       '311 Event Request - 311',
       'Scooter/Bike Shared Dockless Vehicle - TRN',
       'Graffiti City Streets & Bridges - TPW',
       'Landscaping Violation (Arborist) - PDD',
       'Chemical Spill Urgent - OEQS', 'Water Pollution Urgent - DWU',
       'Traffic Sign - Visibility Obstruction - TPW',
       'Street Sweeping - Thoroughfares - PBW', 'TEST CRM',
       'Objects Dropped in Inlet - Hazardous - PBW',
       'Guardrail Repair - Hazardous - TPW',
       'City Property Management/ Real Estate - SDC',
       'Historic District Violation - OHP', 'Street/Road Blockage - TRN',
       'Animal Illegal Vending - DAS',
       'Drainage Ditch Cleaning/Repairs - PBW',
       'Creek/Culvert Maintenance -DWU', 'Steel Plates in Street - TPW',
       'Illegal Dumping Sign - CCS', 'Sanitation Helping Hands - SAN',
       'Conservation District Violation - PNV',
       'Fair Housing Complaint - OHCE',
       'Bike Lane Marking Maintenance – TRN'], dtype=object)